### ISSUE TITLE
WP1.1 - Meteor detection algorithm refinement

### ISSUE THREAD

**Issue by tomoinn** [camsci/meteor-pi#11]
Start to actually pick up observations of meteors. We don't necessarily expect this to be perfect but if we can't get any observations at this point we should probably start worrying about the capabilities of the camera hardware and investigate alternatives.

**Comment by dcf21** [comment]
This milestone is likely to slip a little, but hopefully not too much.

I've spent the past few days doing battle with libav, getting it to decode pre-recorded H264 video from the camera into a buffer for analysis. This has been much harder than I expected: the libav example codes on the web are mostly 10-15 years old, and the API has changed a bit. Even once I'd got them to compile they were producing hideous artifacts in the decoded video.

After lots of experimentation and reading the libav source code, I seem to have found a solution that works.

I'm busy elsewhere on Tue and Wed, but when I get back on Thursday I should have 10 days of unprocessed video and a fast analysis system to run it through. If the analysis go really well I may get a meteor out of the data by Friday; realistically it'll probably take a few days longer...
