### ISSUE TITLE
Check that Tom hasn't done anything too stupid with the python packaging

### ISSUE THREAD

**Issue by tomoinn** [camsci/meteor-pi#26]
...because I've never done this. Check for sanity please? :)

**Comment by dcf21** [comment]
The python packaging looks good to me.

I have a couple of queries about the sql schema in `src/sql/camera_schema.sql`, though.

I still don't like the way `t_cameraStatus` is mixing directly-observable data (e.g. GPS position) and computed data (i.e. orientation).

How do I populate it in practice? I turn a new camera on, and as soon as I get a GPS fix, I know where I am. Where do I record that GPS fix? I don't know where I'm pointing yet. Give it a week and I'll have a pretty good idea, which I may want to be able to retrospectively apply to earlier events.

This would work, I think, if I have rough working table(s) where I can record timestamped GPS fixes and orientation calculations, and then create an entry in `t_cameraStatus` (which is a data product) once I know all the fields (i.e. I've got 20 or so orientation calculations which are converging).

I also think the foreign key relationship between `t_cameraStatus` and `t_occlusion` is the wrong way round -- i.e. `t_cameraStatus` should have a field `occlusion` which references a row in `t_occlusion`. Surely I want to be able to update the orientation to a more refined value without creating a new row in `t_occlusion` every time?

I doubt it will happen very often, but it would be good for the database to be able to cope with me reprocessing last week's data with a different occlusion region. In that case, I need to keep the assocated GPS fixes; I may or may not want to delete last week's orientation calculations, and I ideally only want to have to edit one row in `t_occlusion`. So surely these things need to be stored separately?

Suppose I set up a camera, give it an occlusion polygon, and set it recording a week's video

**Comment by tomoinn** [comment]
In practice you use the API to create a new status object and persist it. It doesn't really matter that it's only partial at this point, we have a way to represent that lack of certainty for orientation.

To update a value, you'll typically retrieve the current one, modify some fields, and save as a new entry. The difference between observed and derived is pretty arbitrary - GPS actually 'observes' timecodes (and possibly phase differences if you're being really fancy) and computes a derived position with a degree of uncertainty, I don't really see this as any different from our observation of the sky and computation of orientation with a degree of uncertainty. Just because we know what's inside the box in one case and not the other doesn't really change the fundamentals.

The way the schema is structured is intended to avoid complexity of re-using previous values. We don't need to - the data is small and not particularly frequently updated, storing the occlusion regions multiple times is no big deal and simplifies things a lot. We optimise for simplicity in this case rather than pure database optimisation, your approach is technically correct in that it minimises redundancy in the DB but in this case that doesn't matter and it would introduce greater code complexity - code is more expensive than a few database inserts in this case.

For the case of re-running with different occlusion regions, this is no different from re-running with a different orientation (if we use my version of the model). You get the current status, set the high water mark (which should scrub any data products after that point), modify then set the status for that time point and let everything re-run.

**Comment by dcf21** [comment]
That works.

Can I have some python API calls for adding events and images into the database, and pulling out a list of them? I'm getting to the point where I really want to be able to start recording metadata on images, e.g. sky clarity indexes and astrometry estimates, and it'd make sense to start putting that in the database.

Next week, Dave and I are planning to set up a handful of different cameras looking through Dave's skylight, to see whether cheaper cameras produce workable video quality. We've also been experimenting with a variety of different lenses.

For the time being I'm hard-coding the lens properties whenever I change it, but it would be useful at some point to be able to look up in the database what lens was attached to which camera on which night, and pull out some metadata about that lens (specifically the lens corrections associated with it). I think we're close to having this, but we need to add a table for lens metadata?

**Comment by dcf21** [comment]
Actually, lens and camera metadata probably sits more naturally in XML files in the source tree, rather than SQL, doesn't it? Nodes will never change it, but we do want to be able to pull updated versions. So having version control will be really handy. I'm thinking out loud....

**Comment by tomoinn** [comment]
I was thinking it would be sensible to have lens and camera metadata tables just on github, so we're thinking along the same lines there. I don't know whether I'd use XML or just CSV - the latter could be simpler, edit in a spreadsheet app of some kind and we don't really need the 'X' in XML do we?

I'm working on the Python API at the moment - was stalled for a couple of days trying to find a transaction bug, turned out to actually be an issue with the relative precision of datetime in Python and timestamp in FirebirdDB.

**Comment by tomoinn** [comment]
(we should probably not be having this conversation in github issue comments... I'm going to close this issue and we can use slack or some other format)
