### ISSUE TITLE
filenames of images in database

### ISSUE THREAD

**Issue by dcf21** [camsci/meteor-pi#30]
Presently, FileRecord objects don't have a "filename" field. Insofar as I can see, to actually access the file, I need to do:

os.path.join(fdb_handle.file_store_path,file_record.file_id.hex)

Suggest setting a "filename" field in the FileRecord object to equal this string? (this needs to be something kids can access really easily)

**Comment by tomoinn** [comment]
Won't work - the kids won't be running code on the camera's pi or the central server so there's no file system to work with. The server needs to be serving those files out, and either the API client or the service itself providing the URIs for them which can then be used to fetch the file data.

**Comment by tomoinn** [comment]
I guess an alternative would be to instantiate the FileRecord objects with a get_file() function which would resolve to a stream, and leave it up to the API client / database client to handle it properly, either opening a stream directly from the file or over HTTP

**Comment by dcf21** [comment]
With you. So the kids will pass the FileRecord object to some FileFetch method which downloads it (or similar). I think it would be good to sketch out what a piece of code will look like to make a timelapse video or stack images together -- I think Dave's right that both want to be 10 line jobs.

As regards code I'm writing code to run on the camera, are you happy with me using the incantation above? (i.e. it's not likely to change ever?)

**Comment by tomoinn** [comment]
Sure, that's how it's going to be stored on camera. I think just having FileRecord include a get_url method is the simplest, and leave it up to the calling code whether it wants to get the file now or later, and asynchronously or synchronously.

**Comment by tomoinn** [comment]
It would be neater to just add a get_filename() method to FileRecord instances on the camera itself though, that way your client code doesn't have to carry a reference to the database configuration around anywhere it needs to resolve files.

**Comment by dcf21** [comment]
Agreed. A get_url() function would work, but I reckon we also want a methods to dump a file into the local filesystem, open it directly as a Python Imaging Library (PIL) object, or maybe even open it on screen.

Somewhere in the kids' API we probably want a function where they can supply an (optional!) camera ID and time, and have a picture of the sky appear on the screen in one line of code.
