### ISSUE TITLE
How do we store the path of a meteor?

### ISSUE THREAD

**Issue by dcf21** [camsci/meteor-pi#31]
The video processing software can now produce a list of all frames in which a meteor appears. A JSON-encoded list of [x,y,time] data can be up to 16kB. Where do we store this? As a metadata field in the database, or in a file that we associate with the event?

Do we still want to store three points extracted from this list in the database as a means of rendering quick-and-dirty Bezier curves through meteors, without having to fetch another chunk of data?

**Comment by tomoinn** [comment]
We need to store this data in a file attached to the event - metadata values can't be large, and shouldn't be changed to be so as we often have to pass them around whether they're needed or not. Keep a summary in the metadata key (start, end etc) as well as an event duration.

**Comment by tomoinn** [comment]
Partially described in https://github.com/camsci/meteor-pi/wiki/List-of-semantic-types, we could do with a bit more detail on the actual format it contains (in particular how times are represented, as there are many many ways to do this...)

**Comment by dcf21** [comment]
Are you happy for us to settle on floating-point Unix times? They're an awful lot easier than anything else as they work cross-language, time arithmetic is easy, and there's no time zone confusion.

**Comment by tomoinn** [comment]
I'm using unix times everywhere else so that would be ideal, for the
reasons you outline.

On 10 June 2015 at 18:08, Dominic Ford notifications@github.com wrote:

> Are you happy for us to settle on floating-point Unix times? They're an
> awful lot easier than anything else as they work cross-language, time
> arithmetic is easy, and there's no time zone confusion.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/camsci/meteor-pi/issues/31#issuecomment-110837658.

## 

Tom Oinn, Director, Cryptic Squid Ltd.
+44 (0) 20 8123 5142 or Skype ID 'tomoinn'
http://www.crypticsquid.com

**Comment by tomoinn** [comment]
Times in the db are now millisecond precision unix timestamps. Where datetime.datetime objects are used these are UTC based. The model has methods to help with this - a method to get the datetime now (called 'now()') and two to convert between the unix timestamps we hold in the db and python datetime.datetime. Use these when handling times or bad things will almost certainly happen.
