### ISSUE TITLE
Python datetime module and Unix times

### ISSUE THREAD

**Issue by dcf21** [camsci/meteor-pi#41]
I just made the following grim discovery:

```
>>> import datetime
>>> import time
>>> dt = datetime.datetime.now()
>>> time.mktime( dt.timetuple() )
1434678196.0
>>> dt2 = datetime.datetime.utcnow()
>>> time.mktime( dt2.timetuple() )
1434674612.0
```

In short, python datetime objects don't store any timezone information. If you create a datetime object with a calendar time in local time (which is the default behaviour), and convert it to a Unix time (using Python's exceptionally verbose syntax), you get the wrong answer.

I'm not sure how much this screws us up. When I insert things into the database, all datetime objects are in UTC (which is the only sane thing for it to do).

Users will almost certainly expect to supply datetimes in local time. In summer there'll be an hour offset.

Now I remember why I always end up using raw unix times, and writing my own utility functions to turn them to/from calendar dates using tzdata...

**Comment by tomoinn** [comment]
It's a mess, as everything involving dates tends to be. On the wire the encoding is to use the raw unix time, so at least that bit's sane. If you look at what's actually produced by datetime.timetuple() there's no timezone information there (although there potentially is in the datetime itself), in fact we have our own version of that logic used when generating unix timestamps from datetime and vice versa when serializing objects for the API. I think therefore that it should just be a question of ensuring that datetimes stored in the DB are UTC, which probably does involve a sweep through the code looking for datetime.now() instances. If users expect to be using local times, well, tough frankly.

**Comment by tomoinn** [comment]
One problem you've hit is that mktime() assumes local timezone. If you're passing a UTC time into it you need calendar.gmtime(). Don't ask...

```
>>> d1 = datetime.datetime.now()
>>> d2 = datetime.datetime.utcnow()
>>> time.mktime(d1.timetuple())
1434703097.0
>>> calendar.timegm(d2.timetuple())
1434703104
```

All these are seconds since epoch.

So the serialization logic needs changing to use calendar.timegm() and we need to only ever store UTC dates in the database. Given those changes I think we're good.

**Comment by tomoinn** [comment]
Of course, we could just store integer epoch timestamps in the db and have done with it, but I quite like the date support.

**Comment by tomoinn** [comment]
Although, that said, I don't entirely trust firebird or the python db api to not silently map timezones. It's really hard to find any documentation that says what they're doing. I think storing int (maybe float) epoch times in the db is the only safe way to handle this.
