### ISSUE TITLE
Firebird's python binding can report "too many open handles to database" under heavy load

### ISSUE THREAD

**Issue by dcf21** [camsci/meteor-pi#42]
If I run the following code:

``` python
import meteorpi_fdb as fdb
f = meteorpi_fdb.MeteorDatabase("localhost:/var/lib/firebird/2.5/data/meteorpi.fdb","~/camsci/meteor-pi/datadir")
for x in range(100000):
  y = f.get_high_water_mark("b827ebd8cc43")
```

I get the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/meteorpi_fdb-0.1.1-py2.7.egg/meteorpi_fdb/__init__.py", line 598, in get_high_water_mark
    (camera_id,))
  File "/usr/local/lib/python2.7/dist-packages/fdb-1.4.5-py2.7.egg/fdb/fbcore.py", line 3371, in execute
    self._ps = PreparedStatement(operation, self, True)
  File "/usr/local/lib/python2.7/dist-packages/fdb-1.4.5-py2.7.egg/fdb/fbcore.py", line 2002, in __init__
    "Error while preparing SQL statement:")
fdb.fbcore.DatabaseError: ('Error while preparing SQL statement:\n- SQLCODE: -904\n- too many open handles to database', -904, 335544761)
```

I'm guessing in short the python garbage collector isn't very good at closing firebird cursors. The scenario I've found that triggers this is trying to import a week's data into the database in one go with lots of calls to register_file().

Hopefully this won't happen in production... but might be worth explicitly closing firebird cursors?

**Comment by tomoinn** [comment]
Yup, the newer database code uses 'with closing(self.con.cursor()) cur:' type constructs, I'll change the rest of the cases to use that form as well. Ensures they're closed on completion.

**Comment by dcf21** [comment]
Thanks @tomoinn . Works a treat.
