### ISSUE TITLE
WP1.1 - Camera image processing validation

### ISSUE THREAD

**Issue by tomoinn** [camsci/meteor-pi#8]
Assemble enough of the camera hardware to validate that images can be captured from the camera module and processed by the main board, and that events can be detected.

Note - for this issue we don't need to detect meteors perfectly, or possibly at all, just that we're linking everything together, we don't have glitches or breaks in the data streams, no unexpected reboots etc. Basically attempting to establish a stable hardware platform and work through any glitches we find.

**Comment by dcf21** [comment]
The Mk I pi camera has now been working for two weeks of real-time event detection and one week of recording video for subsequent processing, without glitches. I anticipate that switching to a Mk II Pi ought to improve stability rather than vice versa.
